version: '3.3'

services:
  database:
    image: 'postgres:15'
    container_name: backend-db
    restart: always
    tty: true
    ports:
      - "${PORT}:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data/
    
  pgadmin:
    image: dpage/pgadmin4
    container_name: backend-pgadmin
    tty: true
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD}"
    ports:
      - "8080:80"
    depends_on:
      - database
